export { WIN_MESSAGES, LOSE_MESSAGES, DRAW_MESSAGES } from "./xoxMessages";
export { WHAT_I_DO_CARDS } from "./whatIDo";
export type { WhatIDoCard } from "./whatIDo";
export { SOCIAL_LINKS, SUBSTACK_LINK } from "./socialLinks";
export type { SocialLink } from "./socialLinks";
export { TECH_STACK } from "./techStack";
export type { SkillCategory } from "./techStack";
export { BLOGS, HACKZISM_BLOG, BIBLIOSMIA_BLOG, BLOG_POSTS } from "./blogs";
export type { Blog, BlogPost, LegacyBlogPost } from "./blogs";
export { EDUCATION, JOURNEY_MILESTONES, EXPERIENCES, PHILOSOPHY_QUOTE } from "./about";
export type { Education, JourneyMilestone, Experience } from "./about";
export { PROJECTS } from "./projects";
export type { Project } from "./projects";
export { SERVICES } from "./services";
export type { Service } from "./services";
export { NAV_LINKS, LOGO_TEXT, CTA_LINK } from "./navigation";
export type { NavLink } from "./navigation";
